### PR TITLE
[MIDDLEWARE] OT226-34  Ownership Middleware

### PR DESCRIPTION
**Pull request by Franckfer**
CARD [OT226-34](https://alkemy-labs.atlassian.net/browse/OT226-34)
<hr>

### Description

Acceptance criteria:

AS a user
I WANT to access only the sections that are allowed for my role.
TO complete certain actions.

Acceptance criteria:
Will be used to protect endpoints that are only for the current user. You must verify the id parameter and compare it with the ID of the user sent in the JWT token, otherwise it will return error 403. However, if the user sent in the token is an administrator, it will allow you to continue.

<hr>

### Evidence

AdminUser
TestApproved
TestApprovedAdmin
Forbiden

### CODE REVIEW

**Review by dangello-g — APPROVED** [review]
Buen PR

**Review by gabodmc — APPROVED** [review]
Lo veo muy bien!

**Review by raoole20 — APPROVED** [review]
Te quedo bien, muy buen PR

**Review by afrivera — APPROVED** [review]
lo veo bien, Buen PR

**Pull request merged**
