### PR TITLE
[SLIDES] - OT226-29  Create migration and Slides model

### PR DESCRIPTION
**Pull request by Franckfer**
CARD [OT226-29](https://alkemy-labs.atlassian.net/browse/OT226-29)
<hr>

### Description

AS an administrator user
I WANT to manage images
TO efficiently modify the visual content

Acceptance criteria:
Slides on the home screen will be dynamically managed by the site administrator. They will have as fields imageUrl, text, order and organizationId (since they will belong to an ngo).

<hr>

### Evidence

DER

Slides

### CODE REVIEW

**Review by gabodmc — APPROVED** [review]
Muy bien resuelto

**Review by Raikul — APPROVED** [review]
Buen PR

**Review by afrivera — APPROVED** [review]
Excelente, buen PR

**Review by dangello-g — APPROVED** [review]
Buen PR

**Pull request merged**
