### PR TITLE
[OT226-33] - Endpoint delete user

### PR DESCRIPTION
**Pull request by afrivera**
### Description

- AS User
- I WANT to delete a user
- TO unsubscribe from the system

### Criteria of acceptance:
DELETE a /users/:id  You should receive the user's id with the DELETE method. The deletion must be logical.

### Evidences
user deleted

### DB show user Table
user deleted en db

### CODE REVIEW

**Comment by raoole20** [comment]
Buen pr bro!

**Review by raoole20 — APPROVED** [review]

**Review by gabodmc — APPROVED** [review]
Muy buen PR. Recordar para proximos casos, en la evidencia, no solo poner el happy path

**Review by nicoescudero — APPROVED** [review]
Buen PR!

**Review by dangello-g — APPROVED** [review]
Buen PR

**Pull request merged**
