### PR TITLE
[ENDPOINT] OT226-48  PUT /news/:id

### PR DESCRIPTION
**Pull request by Franckfer**
CARD [OT226-48](https://alkemy-labs.atlassian.net/browse/OT226-48)

<hr>

## Description

* AS admin user
* I WANT to update an existing news
* TO keep the information updated.

### Acceptance criteria:

PUT /news/:id - It must validate that the news exists based on the id sent by parameter. If it does not exist, it returns an error, otherwise it updates the news and returns it with the updated data.

<hr>

## Evidence

**Admin User**
AdminUser

**Not Admin User**
NotAdminUser

**Update News**
updateNews

**News Not Found**
newsNotFound

### CODE REVIEW

**Review by gabodmc — COMMENTED** [review]
Lo veo bien. Podras agregar evidencia de si no es admin?

**Review by dangello-g — APPROVED** [review]
Buen PR

**Review by afrivera — APPROVED** [review]
Pinta bien, buen PR

**Comment by Franckfer** [comment]
> Lo veo bien. Podras agregar evidencia de si no es admin?

si lo agrego

**Review by gabodmc — APPROVED** [review]
Excelente!

**Pull request merged**
